language: java

branches:
    only:
      - master
cache:
  directories:
    - '${HOME}/.cache/html'
    
# Travis CI 서버의 Home

# before_install:
#   - npm install -g yarn@1.21.1
script:
   - echo "skipping tests"

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: jaehoon-dayoff.ml # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    acl: public_read
    skip_cleanup: true
    on:
      repo: hoonsbory/ToneTest #Github 주소
      branch: master
